# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    offer.provider:
        class: AppBundle\Services\OfferProvider

    sdk.offer.manager:
        class: AppBundle\Services\SDKOfferManager
        arguments: ["@request_stack", "@url.generator", "@transaction.id.generator", "@offer.provider", "@validator", "@doctrine.orm.entity_manager"]

    skype.offer.manager:
            class: AppBundle\Services\SkypeOfferManager
            arguments: ["@offer.provider", "@url.generator",  "@security.token_storage", "@doctrine.orm.entity_manager", "@validator"]

    url.generator:
            class: AppBundle\Services\UrlGenerator
            #arguments: []
    cache:
            class: AppBundle\Services\Cache
            arguments: ["%kernel.environment%"]

    database.compressor:
            class: AppBundle\Services\DatabaseCompressor
            arguments: ["@doctrine.orm.entity_manager"]

    transaction.id.generator:
            class: AppBundle\Services\TransactionIdGenerator
            arguments: ["@request_stack", "@url.generator", "@doctrine.orm.entity_manager"]

    publisher.validator:
            class: AppBundle\Services\PublisherValidator
            arguments: ["@validator"]

    api.token_authenticator:
        class: ApiOutBundle\Security\TokenAuthenticator
        arguments: ["@doctrine.orm.entity_manager"]

    partner_api.token_authenticator:
            class: PartnerApiBundle\Security\PartnerApiTokenAuthenticator
            arguments: ["@doctrine.orm.entity_manager"]

    skype_api.token_authenticator:
            class: SkypeApiBundle\Security\SkypeApiTokenAuthenticator
            arguments: ["@doctrine.orm.entity_manager"]

    date.event.listener:
        class: AppBundle\EventListener\DateDoctrineListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    api.controller.listner:
         class: AppBundle\EventListener\ApiControllerListener
         arguments: ["@doctrine.orm.entity_manager"]
         tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
